import { Controller, eventListener } from '@a11d/lit'
import { DataGridColumnComponent } from './columns/DataGridColumnComponent.js'
import { type DataGridColumn } from './controller/DataGridColumn.js'
import { type DataGrid } from './DataGrid.js'

/** The column elements of a `mo-data-grid`: the ones it is declared with, and the ones it makes up for data it has no columns for. */
export class DataGridColumnComponentsController<TData> extends Controller {
	constructor(private readonly grid: DataGrid<TData, any>) {
		super(grid)
	}

	private initialized = false

	override hostUpdated() {
		if (!this.initialized && !this.grid.columnDefinitions.extracted.length) {
			this.extractColumns()
		}
		this.initialized = true
	}

	@eventListener('DataGridColumnComponent:update')
	protected handleColumnChange(e: CustomEvent) {
		e.stopPropagation()
		this.extractColumns()
	}

	extractColumns() {
		this.grid.columnDefinitions.extracted = this.columnsElements.map(c => c.column)
	}

	private get columnsElements() {
		const slot = this.grid.renderRoot?.querySelector<HTMLSlotElement>('slot[name=column]')
		if (!slot) {
			return []
		}
		const children = [...slot.children]
		const assigned = [...slot.assignedElements()]
		return [...assigned, ...children]
			.filter((c): c is DataGridColumnComponent<TData, any> => c instanceof DataGridColumnComponent)
			.map(c => {
				c.dataGrid = this.grid
				return c
			})
	}

	get autoGeneratedColumns(): Array<DataGridColumn<TData>> {
		if (!this.grid.data.length) {
			return []
		}

		const getDefaultColumnElement = (value: unknown) => {
			switch (typeof value) {
				case 'number':
				case 'bigint':
					return 'mo-data-grid-column-number'
				case 'boolean':
					return 'mo-data-grid-column-boolean'
				default:
					return 'mo-data-grid-column-text'
			}
		}
		const [sampleData] = this.grid.data
		return Object.keys(sampleData || {})
			.filter(key => !key.startsWith('_'))
			.map(key => {
				const columnElement = document.createElement(getDefaultColumnElement(KeyPath.get(sampleData, key as any)))
				columnElement.heading = key.replace(/([A-Z])/g, ' $1').charAt(0).toUpperCase() + key.replace(/([A-Z])/g, ' $1').slice(1)
				columnElement.dataSelector = key
				columnElement.dataGrid = this.grid as unknown as DataGrid<unknown, any>
				return columnElement.column
			}) as unknown as Array<DataGridColumn<TData>>
	}
}
