name: 🔍 Quality Assurance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  type-check:
    name: 🏗️ Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run typescript

  lint:
    name: 📝 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test
