import { Controller } from '@a11d/lit'
import { DataGridColumnComponent, type DataGrid, type DataGridColumn } from '../index.js'
import { DataGridColumns } from './DataGridColumns.js'

/**
 * Connects a data grid to its columns, feeding them the definition sources it observes — the column
 * elements and the data — and reflecting them back into the data grid's rendering.
 *
 * @see DataGridColumns for the columns themselves and the layers they are composed of.
 */
export class DataGridColumnsController<TData> extends Controller {
	private readonly columnWidths = { reordering: 0, details: 0, selection: 0, actions: 0 }
	private readonly widthsInPixels = new Map<KeyPath.Of<TData>, number>()
	private initialized = false

	// Created on first access rather than initialized inline, as composing columns reads from the host
	private _columns?: DataGridColumns<TData>
	get columns() {
		return this._columns ??= new DataGridColumns<TData>({
			generate: () => this.autoGeneratedColumns,
			prepare: column => column.dataGrid = this.host,
			updated: () => this.columnsUpdated(),
		})
	}

	constructor(override readonly host: DataGrid<TData, any>) {
		super(host)
	}

	override hostUpdate() {
		this.provideCssColumnsProperties()
	}

	override hostUpdated() {
		if (!this.initialized && !this.columns.definitions.extracted.length) {
			this.extractColumns()
		}
		this.initialized = true
	}

	private columnsUpdated() {
		this.host.columnsChange.dispatch([...this.columns])
		this.host.requestUpdate()
	}

	extractColumns() {
		this.columns.definitions.extracted = this.columnsElements.map(c => c.column)
	}

	private get columnsElements() {
		const slot = this.host.renderRoot?.querySelector<HTMLSlotElement>('slot[name=column]')
		if (!slot) {
			return []
		}
		const children = [...slot.children]
		const assigned = [...slot.assignedElements()]
		return [...assigned, ...children]
			.filter((c): c is DataGridColumnComponent<TData, any> => c instanceof DataGridColumnComponent)
			.map(c => {
				c.dataGrid = this.host
				return c
			})
	}

	getWidthInPixels(dataSelector: KeyPath.Of<TData>) {
		return this.widthsInPixels.get(dataSelector)
	}

	setWidthInPixels(dataSelector: KeyPath.Of<TData>, width: number) {
		this.widthsInPixels.set(dataSelector, width)
	}

	// The reason for not doing this in the CSS is that we need to trim all the 0px values out of the columns
	// because the 'grid column gap' renders a gap no matter if the column is 0px or not
	private provideCssColumnsProperties() {
		const columns = this.cssColumns.map(c => `[${c.name}] ${c.width}`).join(' ')
		if (this.host.style.getPropertyValue('--mo-data-grid-columns') !== columns) {
			this.host.style.setProperty('--mo-data-grid-columns', columns)
		}
	}

	private get cssColumns() {
		const order = !this.host.reorderabilityController.enabled ? undefined : window.getComputedStyle(this.host).getPropertyValue('--mo-data-grid-column-reorder-width')
		const details = !this.host.hasDetails ? undefined : window.getComputedStyle(this.host).getPropertyValue('--mo-data-grid-column-details-width')
		const selection = !this.host.hasSelection ? undefined : window.getComputedStyle(this.host).getPropertyValue('--mo-data-grid-column-selection-width')
		const data = this.columns.visible
			.map(c => c.width)
			.filter((c): c is string => c !== undefined)
		const actions = window.getComputedStyle(this.host).getPropertyValue('--mo-data-grid-column-actions-width')
		return [
			{ name: 'order', width: order },
			{ name: 'details', width: details },
			{ name: 'selection', width: selection },
			...data.map(width => ({ name: 'data', width })),
			{ name: 'padding', width: '1fr' },
			{ name: 'actions', width: actions }
		].filter(c => c.width !== undefined) as Array<{ readonly name: string, readonly width: string }>
	}

	private get autoGeneratedColumns(): Array<DataGridColumn<TData>> {
		if (!this.host.dataLength) {
			return []
		}

		const getDefaultColumnElement = (value: unknown) => {
			switch (typeof value) {
				case 'number':
				case 'bigint':
					return 'mo-data-grid-column-number'
				case 'boolean':
					return 'mo-data-grid-column-boolean'
				default:
					return 'mo-data-grid-column-text'
			}
		}
		const [sampleData] = this.host.data || []
		return Object.keys(sampleData || {})
			.filter(key => !key.startsWith('_'))
			.map(key => {
				const columnElement = document.createElement(getDefaultColumnElement(KeyPath.get(sampleData, key as any)))
				columnElement.heading = key.replace(/([A-Z])/g, ' $1').charAt(0).toUpperCase() + key.replace(/([A-Z])/g, ' $1').slice(1)
				columnElement.dataSelector = key
				columnElement.dataGrid = this.host as DataGrid<unknown, any>
				const column = columnElement.column
				columnElement.remove()
				return column
			}) as Array<DataGridColumn<TData>>
	}

	setColumnWidth(column: keyof typeof this.columnWidths, widthInPixels: number) {
		this.columnWidths[column] = widthInPixels
	}

	getStickyColumnInsetInline(column: DataGridColumn<TData> | keyof typeof this.columnWidths) {
		const widths = {
			reordering: !this.host.reorderabilityController.visible ? 0 : this.columnWidths.reordering,
			details: !this.host.hasDetails ? 0 : this.columnWidths.details,
			selection: !this.host.hasSelection ? 0 : this.columnWidths.selection,
			actions: !this.host.hasContextMenu ? 0 : this.columnWidths.actions
		}
		if (typeof column !== 'object') {
			switch (column) {
				case 'reordering':
					return '0px'
				case 'selection':
					return `${widths.reordering}px`
				case 'details':
					return `${widths.reordering + widths.selection}px`
				case 'actions':
					return 'auto'
			}
		}

		if (!column.sticky) {
			return ''
		}

		const visibleColumns = this.columns.visible
		const columnIndex = visibleColumns.indexOf(column)
		const calculate = (type: 'start' | 'end') => visibleColumns
			.filter((c, i) => c.sticky === type && (type === 'start' ? i < columnIndex : i > columnIndex))
			.map(c => c.widthInPixels)
			.filter(x => x !== undefined)
			.reduce((a, b) => a! + b!, 0)!

		const start = `${widths.reordering + widths.selection + widths.details + calculate('start')}px`
		const end = `${calculate('end') + widths.actions}px`

		switch (column.sticky) {
			case 'start':
				return `${start} auto`
			case 'end':
				return `auto ${end}`
			case 'both':
				return `${start} ${end}`
			default:
				return ''
		}
	}
}